type Answer {
  _id: String!
  body: String!
  owner: User!
  votes: Votes!
  postedOn: String
  editedBy: [User!]!
  editedOn: String!
}

input AnswerRDInp {
  _id: String!
}

input AnswerCreateInp {
  body: String!
  owner: String!
  question: String!
}

input AnswerUpdateInp {
  body: String!
}
