type Question {
  _id: String!
  title: String!
  body: String!
  views: String!
  isSuspended: Boolean!
  votes: Votes!
  owner: User!
  answers: [Answer!]!
  tags: [String!]!
  postedOn: String
  editedBy: [User!]!
  editedOn: String!
}

input QuestionRDInp {
  _id: String!
}

input QuestionCreateInp {
  title: String!
  body: String!
  owner: String!
  tags: [String!]
}

input QuestionUpdateInp {
  title: String
  body: String
}
