# import Answer, AnswerRDInp, AnswerCreateInp, AnswerUpdateInp from "./answer.gql"
# import Question, QuestionRDInp, QuestionCreateInp, QuestionUpdateInp from "./question.gql"
# import User, UserRDInp, UserCUInp from "./user.gql"


type QueryResolver {
    getAnswer(args: AnswerRDInp): Answer!
    getQuestion(args: QuestionRDInp): Question!
    getUser(args: UserRDInp): User!
}

type MutationResolver {
    # Answer
    createAnswer(args: AnswerCreateInp): Boolean!
    updateAnswer(args: AnswerUpdateInp): Boolean!
    deleteAnswer(args: AnswerRDInp): Boolean!
    # Question
    createQuestion(args: QuestionCreateInp): Boolean!
    updateQuestion(args: QuestionUpdateInp): Boolean!
    deleteQuestion(args: QuestionRDInp): Boolean!
    # User
    createUser(args: UserCUInp): Boolean!
    updateUser(args: UserCUInp): Boolean!
    deleteUser(args: UserRDInp): Boolean!
}


schema {
    query: QueryResolver
    mutation: MutationResolver
}
