type User {
  _id: String! # Username
  isBanned: Boolean!
  reputation: Int!
  name: String!
  bio: String!
  email: String!
  questions: [Question!]!
  answers: [Answer!]!
  joinedOn: String!
  level: Int!
}

input UserRDInp {
  _id: String!
}

input UserCreateInp {
  uname: String!
  name: String!
  bio: String!
  email: String!
}

input UserUpdateInp {
  name: String
  bio: String
  email: String
}
